channel_buffer_size = 100

[write]
  concurrency = 10
  batch_size = 5000
  batch_interval = "4s"
  database = "stress"
  precision = "n"
  address = "localhost:8086"
  reset_database = true
  starting_point = 4 # how far back in time to go in weeks

[[series]]
  point_count = 10000 # number of points that will be written for each of the series
  measurement = "cpu"
  series_count = 100000

  [[series.tag]]
    key = "host"
    value = "server"

  [[series.tag]]
    key = "location"
    value = "loc"

  [[series.field]]
    key = "value"
    type = "float64"

