project_name: influxdb2
builds:
  - id: influx
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: arm64
    main: ./cmd/influx/
    flags:
      - -tags={{if eq .Os "linux"}}osusergo,netgo,static_build{{if not (eq .Arch "amd64")}},noasm{{end}}{{end}}
      - -buildmode={{if eq .Os "windows"}}exe{{else}}pie{{end}}
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - CC=musl-gcc
      - PKG_CONFIG=$GOPATH/bin/pkg-config
    ldflags:
      - -s -w -X main.version=nightly -X main.commit={{.ShortCommit}} -X main.date={{.Date}} {{if eq .Os "linux"}}-extldflags "-fno-PIC -static -Wl,-z,stack-size=8388608"{{end}}
    binary: influx

  - id: influxd
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: arm64
    main: ./cmd/influxd/
    flags:
      - -tags=assets{{if eq .Os "linux"}},osusergo,netgo,static_build{{if not (eq .Arch "amd64")}},noasm{{end}}{{end}}
      - -buildmode={{if eq .Os "windows"}}exe{{else}}pie{{end}}
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - CC=musl-gcc
      - PKG_CONFIG=$GOPATH/bin/pkg-config
    ldflags:
      - -s -w -X main.version=nightly -X main.commit={{.ShortCommit}} -X main.date={{.Date}} {{if eq .Os "linux"}}-extldflags "-fno-PIC -static -Wl,-z,stack-size=8388608"{{end}}
    binary: influxd
    hooks:
      pre: make generate

# Do not make github release
release:
  disable: true
