description: Represents a complete package source tree.
type: object
properties:
  type:
    $ref: "#/components/schemas/NodeType"
  path:
    description: Package import path
    type: string
  package:
    description: Package name
    type: string
  files:
    description: Package files
    type: array
    items:
      $ref: "#/components/schemas/File"
