version: 2.1

executors:
  linux-amd64:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: large

  linux-arm64:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: arm.large

  mac:
    macos:
      xcode: 12.4.0
    resource_class: medium
    shell: /bin/bash -eo pipefail

  windows:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.medium
    shell: bash.exe -eo pipefail

workflows:
  version: 2
  build-and-test:
    jobs:
      - lint
      - build:
          requires:
            - lint
          matrix:
            parameters:
              executor:
                - linux-amd64
                - linux-arm64
                - mac
                - windows
      - package-linux:
          requires:
            - build-linux-amd64
            - build-linux-arm64
      - publish-artifacts:
          requires:
            - package-linux
            - build-mac
            - build-windows
      - test:
          requires:
            - lint
          matrix:
            parameters:
              executor:
                - linux-amd64
                - linux-arm64
                - mac
                - windows
      - perf-test:
          requires:
            - package-linux
            - test

commands:
  setup:
    steps:
      - run:
          name: Install system dependencies
          command: ./scripts/ci/setup-system.sh
      - run:
          name: Install Go
          command: |
            ./scripts/ci/install-go.sh ${HOME}/.tools
            echo 'export PATH=${HOME}/.tools/go/bin:${PATH}' >> $BASH_ENV
      - run:
          name: Set GOPATH and GOCACHE
          command: |
            GOPATH=${HOME}/go
            echo "export GOPATH=${GOPATH}" >> $BASH_ENV
            mkdir -p ${GOPATH}/bin
            echo 'export PATH=${GOPATH}/bin:${PATH}' >> $BASH_ENV
            mkdir -p ${HOME}/.cache
            echo 'export GOCACHE=${HOME}/.cache' >> $BASH_ENV
      - run:
          name: Install Rust toolchain
          command: |
            ./scripts/ci/install-rust.sh
            echo 'export PATH=${HOME}/.cargo/bin:${PATH}' >> $BASH_ENV
      - run:
          name: Install pkg-config wrapper
          command: go build -o "${GOPATH}/bin/" github.com/influxdata/pkg-config

jobs:
  lint:
    executor: linux-amd64
    steps:
      - checkout
      - setup
      - run:
          name: Check flag generation
          command: ./scripts/ci/lint/flags.bash
      - run: make checkgenerate
      - run: make vet
      - run: make checkfmt
      - run: GO111MODULE=on go mod vendor # staticcheck looks in vendor for dependencies.
      - run: GO111MODULE=on go install honnef.co/go/tools/cmd/staticcheck # Install staticcheck from the version we specify in go.mod.
      - run: GO111MODULE=on ./env staticcheck ./...

  build:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - setup
      - run:
          name: Generate assets
          command: make generate
      - run:
          name: Build release binary
          command: |
            DEST=dist/influxd_$(go env GOOS)_$(go env GOARCH)
            mkdir -p "$DEST"
            ./scripts/ci/build-influxd.sh "$DEST"
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - dist

  package-linux:
    docker:
      - image: cimg/go:1.16
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build linux packages
          command: ./scripts/ci/package-linux.sh
      - persist_to_workspace:
          root: .
          paths:
            - dist

  publish-artifacts:
    docker:
      - image: cimg/go:1.16
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Prep artifacts
          command: |
            mkdir artifacts
            ./scripts/ci/prepare-artifacts.sh $(pwd)/artifacts
      # TODO: Inject S3 upload here?
      - store_artifacts:
          path: artifacts

  test:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    parallelism: 8
    steps:
      - checkout
      - setup
      - run:
          name: Download gotestsum
          command: |
            GOTESTSUM_VERSION=1.6.4
            GOTESTSUM_ARCHIVE=gotestsum_${GOTESTSUM_VERSION}_$(go env GOOS)_$(go env GOARCH).tar.gz
            GOTESTSUM_URL=https://github.com/gotestyourself/gotestsum/releases/download/v${GOTESTSUM_VERSION}/${GOTESTSUM_ARCHIVE}

            wget ${GOTESTSUM_URL}
            tar xzf ${GOTESTSUM_ARCHIVE}
            install gotestsum ${GOPATH}/bin/
      - run:
          name: Run race tests
          command: |
            mkdir test-results
            GO_TEST_CMD="gotestsum --format standard-quiet --junitfile ./test-results/gotestsum.xml -- -p=4"
            TESTFILES=($(go list ./... | circleci tests split --split-by=timings))
            make PKG_CONFIG="${GOPATH}/bin/pkg-config" GO_TEST_CMD="$GO_TEST_CMD" GO_TEST_PATHS="${TESTFILES[*]}" test-go-race
      - store_artifacts:
          path: ./test-results
          destination: raw-test-output
      - store_test_results:
          path: ./test-results

  perf-test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "91:0a:5b:a7:f9:46:77:f3:5d:4a:cf:d2:44:c8:2c:5a"
      - run:
          name: Run test in AWS instance
          no_output_timeout: 20m
          command: AWS_ACCESS_KEY_ID=${TEST_AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${TEST_AWS_SECRET_ACCESS_KEY} scripts/ci/perf_test.sh
