post:
  operationId: PostSources
  tags:
    - Sources
  summary: Create a source
  parameters:
    - $ref: "#/components/parameters/TraceSpan"
  requestBody:
    description: Source to create
    required: true
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/Source"
  responses:
    "201":
      description: Created Source
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Source"
    default:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
get:
  operationId: GetSources
  tags:
    - Sources
  summary: Get all sources
  parameters:
    - $ref: "#/components/parameters/TraceSpan"
    - in: query
      name: org
      description: The organization name.
      schema:
        type: string
  responses:
    "200":
      description: All sources
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Sources"
    default:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
