[[measurements]]
name   = "2t10v1000000p"
sample = 1.0
tags = [
    { name = "tag0", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
    { name = "tag1", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
]
fields = [
    { name = "v0", count = 10000, source = 1.0 },
]

[[measurements]]
name   = "3t10v1000000p"
sample = 1.0
tags = [
    { name = "tag0", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
    { name = "tag1", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
    { name = "tag2", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
]
fields = [
    { name = "v0", count = 1000, source = 1.0 },
]

[[measurements]]
name   = "4t10v1000000p"
sample = 1.0
tags = [
    { name = "tag0", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
    { name = "tag1", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
    { name = "tag2", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
    { name = "tag3", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
]
fields = [
    { name = "v0", count = 100, source = 1.0 },
]

[[measurements]]
name   = "5t10v1000000p"
sample = 1.0
tags = [
    { name = "tag0", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
    { name = "tag1", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
    { name = "tag2", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
    { name = "tag3", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
    { name = "tag4", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
]
fields = [
    { name = "v0", count = 10, source = 1.0 },
]

[[measurements]]
name   = "6t10v1000000p"
sample = 1.0
tags = [
    { name = "tag0", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
    { name = "tag1", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
    { name = "tag2", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
    { name = "tag3", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
    { name = "tag4", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
    { name = "tag5", source = { type = "sequence", format = "value%s", start = 0, count = 10 } },
]
fields = [
    { name = "v0", count = 1, source = 1.0 },
]